# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Comment

# Model Form Field configuration
form: $/zisoft/comments/models/comment/fields.yaml

# Model Class name
modelClass: Zisoft\Comments\Models\Comment

# Default redirect location
defaultRedirect: zisoft/comments/comments

# Create page
create:
    title: zisoft.comments::lang.backend.form.create
    redirect: zisoft/comments/comments/update/:id
    redirectClose: zisoft/comments/comments

# Update page
update:
    title: zisoft.comments::lang.backend.form.update
    redirect: zisoft/comments/comments
    redirectClose: zisoft/comments/comments

# Preview page
preview:
    title: zisoft.comments::lang.backend.form.preview
